/*
 * cmd.h
 *
 *  Created on: 2009-10-16
 *      Author: root
 */

#ifndef _COMMON_CMD_H_
#define _COMMON_CMD_H_

enum //查找在线用户状态描述
{
	ONLINE_USER_END,
	ONLINE_USER_NEXT_PACKET,
	ONLINE_USER_NEXT_PAGE
};

enum //向客户端发送精确查找用户状态包描述
{
	SEARCH_NO_NEXT_INFO,
	SEARCH_HAS_NEXT_INFO
};

enum//状态描述
{
	SS_OFFLINE,//离线
	SS_ONLINE,//在线
	SS_AWAY,//离开
	SS_HIDING,//隐身
	SS_GAMING,//游戏中
	SS_NOLOGIN,//未登录
	SS_DONTBOTHER,//勿打扰
	SS_SUB_AUTO_AWAY,//自动离开
	SS_SUB_AUTO_HIDING,// 自动隐身

	SS_UNDEFINE = 0xFF // 未知状态
};
enum {
	//登录结果
	LOGIN_SUCCESS,
	LOGIN_INVALID_UIN,
	LOGIN_WRONG_PASSWD,

	//校验串结果
	CHECK_SUCCESS,
	CHECK_FAILURE,

	LOGIN_SS_REGISTER_FAIL, // 状态服务器登记失败
	LOGIN_EXCEED_MAX_MULTPT // 超过最大多点个数
};

//绑定结果
enum
{
	BIND_SUCCESS,//绑定成功
	BIND_FAILURE,//绑定失败
	BIND_EXIST,  //已被绑定
	BIND_NONE,    //未绑定（允许绑定）

//取消绑定结果
	CANCEL_BIND_SUCCESS,
	CANCEL_BIND_FAILURE,
};

//各种绑定信息
enum{
	BIND_GAME_FLAG =   0x01,//0001
	BIND_QQ_FLAG =     0x02,//0010
	BIND_EMAIL_FLAG =  0x04,//0100
	BIND_MOBILE_FLAG = 0x08,//1000
	BIND_HASVIDEO = 0x010, //10000S是否有视频头


	CANCEL_BIND_GAME_FLAG =   0x0E,//1110
	CANCEL_BIND_QQ_FLAG =     0x0D,//1101
	CANCEL_BIND_EMAIL_FLAG =  0x0B,//1011
	CANCEL_BIND_MOBILE_FLAG = 0x07,//0111
	CANCEL_BIND_HASVIDEO = 0xEF,   //1110 1111是否有视频头
};

//2人语音聊天状态
enum
{
	VOST_NONE = 0,
	VOST_CONNECTING,
	VOST_CONNECTED,
	VOST_UNDEFINE = 0xFF
};

//多人语音聊天
enum
{
	GROUP_TALK_AUDIO_UNCREATER = 0,
	GROUP_TALK_AUDIO_CREATER,
	GROUP_TALK_AUDIO_UNDEFINE = 0xFF
};

//各种绑定方式
enum
{
	NONE_BIND,//指使用帐号(uin)登录
	AUTO_EMAIL_BIND,
	AUTO_MOBILE_BIND,
	AUTO_QQ_BIND,
	AUTO_GAME_BIND,
	GUIDE_EMAIL_BIND,
	GUIDE_MOBILE_BIND,
	GUIDE_QQ_BIND,
	GUIDE_GAME_BIND,//（需要填写游戏密码的）
	GUIDE_GAME_BIND_NOT_FILL,//（不需要填写游戏密码的，针对在上一个步骤已经输入过密码）
};

enum {
	// -----------------------------
	//需要用户确认和记录离线的消息类型，而且需要通知自己的其他登陆点
	//
	MSG_A2A = 0,//!<二人聊天消息
	///////////////////////
	MSG_AUTH_ACCEPTED,//!<加好友验证通过
	MSG_RESERVED,
	MSG_AUTH_REJECTED,//!<加好友拒绝验证
	MSG_ADDED,//!<被别人加为好友
	MSG_TCP_REQUEST,//!<暂不使用
	MSG_TCP_ACCEPTED,//!<暂不使用
	MSG_TCP_RESPONE,//!<暂不使用
	MSG_TCP_REJECTED,//!<暂不使用
	MSG_P2P_TEXT,//!<暂不使用
	MSG_RESPONE,//!<暂不使用

	MSG_ADDED_RECENT_GAME_PLAYER, //!< 加最近玩家用

	MSG_GROUP_AUTH_REQUEST,//!<加入某群的验证请求[进入创建人处理过程]
	MSG_GROUP_AUTH_ACCEPTED,//!<接收加入某群的验证请求[进入请求人处理过程]
	MSG_GROUP_AUTH_REJECTED,//!<拒绝加入某群验证请求[进入请求人处理过程]
	MSG_GROUP_FORCE_LEAVE,//!<强制某人离开
	MSG_GROUP_INVITE_ENTRY,//!<邀请某人加入

	MSG_OFFLINE_FILE,
	MSG_A2A_IMG_OFFLINE,

	// -----------------------------
	//需要用户确认和记录离线的消息类型，但不需要通知自己的其他登陆点
	//
	MSG_FLAG_DONOT_MULTPT_NOTIFYSELF = 0x40,

	MSG_AUTH_REQUEST,//!<加好友验证请求

	MSG_SVC_A2A_OFFLINE = 84, // 离线消息
	MSG_SVC_GROUP_CHAT = 87,
	MSG_SVC_GROUP_COMMAND_OFFLINE = 88,// 群命令离线消息


	// -----------------------------
	// 不需要用户确认和记录离线的消息类型，但需要通知自己的其他登陆点
	//
	MSG_FLAG_DIRECT = 0x80,

	MSG_A2A_MULTPT_SCENE,//场景更改通知


	// -----------------------------
	// 不需要用户确认和记录离线的消息类型，而且不需要通知自己的其他登陆点
	//
	MSG_FLAG_DIRECT_AND_DONOT_MULTPT_NOTIFYSELF = 0xC0,

	MSG_A2A_TYPING,//!<正在输入的通知
	MSG_A2A_SCENE,//场景更改通知
	MSG_A2A_AUTO_REPLY,
	MSG_RESERVED2,

	MSG_BROADCAST,//系统广播消息类型
	MSG_ADVERT,//系统广告消息

	MSG_RESERVED3,
	MSG_RESERVED4,

	MSG_BROADCAST_HTM,//!<HTM系统广播类型
	MSG_PIRATE_FIGHTER,//!<打击盗版的消息

	MSG_SMS_TEXT,//!<手机短信类型
	MSG_PHOTO_VER_VERIFY,		//!<用于形象照片版本校验
	MSG_PHOTO_VER_VERIFY_REPLY,	//!<形象照片版本校验返回最新的版本

	MSG_RECVSYS_IMSTOSMS = 240,//接受系统消息
	MSG_SEARCHSYS_IMSTOSMS,//查询系统消息
	MSG_SENDSYSALL_SMSTOIMS,//全网消息发送
	MSG_MOSTUSR_SMSTOIMS,//大用户量的消息
	MSG_SENDSYSSAMLL_SMSTOIMS,//系统消息发送－人数少
	MSG_ACK_SMS,//应答IMS的消息



	//End
};


typedef enum _MessageType
{
	// 文件传输
	MESSAGE_TYPE_FILETRANSFER_FIRST = 1000,
	MESSAGE_TYPE_FILETRANSFER_OFFER_REQUEST,				// 请求发送文件
	MESSAGE_TYPE_FILETRANSFER_OFFER_RESPONSE,
	MESSAGE_TYPE_FILETRANSFER_OFFER_ACK,					// ACK
	MESSAGE_TYPE_FILETRANSFER_READY_REQUEST,				// 准备发送文件
	MESSAGE_TYPE_FILETRANSFER_READY_RESPONSE,
	MESSAGE_TYPE_FILETRANSFER_CLOSE,						// 关闭或取消发送文件
	MESSAGE_TYPE_FILETRANSFER_OFFER_OFFLINE_FILE,			// 发送离线文件
	MESSAGE_TYPE_FILETRANSFER_RECEIVED_OFFLINE_FILE,		// 已接收完成离线文件
	MESSAGE_TYPE_FILETRANSFER_LAST = 1099
} MessageType;

typedef enum _MessageFlag
{
	MESSAGE_FLAG_NONE = 0,
	MESSAGE_FLAG_NEED_ACK = 1 << 0,							// 需要用户确认或记录离线
	MESSAGE_FLAG_NEED_NOTIFY_OWN_MULTIPOINT = 1 << 1,		// 需要通知自己的其他登陆点
	MESSAGE_FLAG_TO_ALL_POINT = 1 << 2						// 发送到对方所有登陆点

} MessageFlag;




#define DECLARE_COMMANDS() enum tagCommands {
#define COMMAND_ENTRY_INDEX(cmd, index) cmd = index,
#define COMMAND_ENTRY(cmd) cmd,
#define END_COMMANDS() CMD_END };

DECLARE_COMMANDS()
	COMMAND_ENTRY_INDEX(WY_VER, 1)
	COMMAND_ENTRY(WY_CVR)
	COMMAND_ENTRY(WY_UIN_VERIFY)
	COMMAND_ENTRY(WY_EMAIL_VERIFY)
	COMMAND_ENTRY(WY_MOBILE_VERIFY)//5
	COMMAND_ENTRY(WY_QQ_VERIFY)
	COMMAND_ENTRY(WY_GAME_VERIFY)
	COMMAND_ENTRY(WY_LOGIN)
	COMMAND_ENTRY(WY_LOGOUT)
	COMMAND_ENTRY(WY_NEWUSR)//10
	COMMAND_ENTRY(WY_NEWUSR_MB)
	COMMAND_ENTRY(WY_NEWUSR_GAME)
	COMMAND_ENTRY(WY_NEWSUBUSR)
	COMMAND_ENTRY(WY_GETUSR)
	COMMAND_ENTRY(WY_REAUSR)//15
	COMMAND_ENTRY(WY_CHANGE_STATUS)
	COMMAND_ENTRY(WY_KEEPALIVE)
	COMMAND_ENTRY(WY_ADDFRD)
	COMMAND_ENTRY(WY_REMFRD)
	COMMAND_ENTRY(WY_RENAMEFRD)//20
	COMMAND_ENTRY(WY_LSTFRD)//21
	COMMAND_ENTRY(WY_ADG)//22
	COMMAND_ENTRY(WY_RMG)
	COMMAND_ENTRY(WY_REG)
	COMMAND_ENTRY(WY_LSG)//25
	COMMAND_ENTRY(WY_GET_FRIEND_OF_FRIEND)//26 // 获得对应uin开放的好友对好友设置
	COMMAND_ENTRY(WY_SEARCH_FRIEND)
	COMMAND_ENTRY(WY_GET_GRADE)
	COMMAND_ENTRY(WY_ACK)//29
	COMMAND_ENTRY(WY_BC_MSG)
	COMMAND_ENTRY(WY_SRV_MSG)//31
	COMMAND_ENTRY(WY_MSG)
	COMMAND_ENTRY(WY_EXIST_UIN)
	COMMAND_ENTRY(WY_CHGNICK)//34
	COMMAND_ENTRY(WY_LSTFRDSTATUS)
	COMMAND_ENTRY(WY_MAC_VERIFY)//add by ljh 20041129
	COMMAND_ENTRY(WY_BECOME_FORMAL_USER)//add by ljh 20041213
	// added by baiym : 2009-11-5 10:29 for search friend
	COMMAND_ENTRY(WY_SEARCH_ONLINE_IMS)
	COMMAND_ENTRY(WY_SEARCH_CONDITION_IMS)
	COMMAND_ENTRY(WY_OL_NUM)
	// end added by baiym : 2009-11-5 10:30

	//Add By chenzhao 2009-11-09 use WY_MULTIPOINT_MSG_ACK instead
	COMMAND_ENTRY(WY_MSG_ACK)
	//End
	//add zhengnh 2009 -12-10 获取群离线消息
	COMMAND_ENTRY(WY_GET_GROUPOFFLINEMSG) //NOTE: Deprecated!!!
	COMMAND_ENTRY(WY_GROUP_MSG_ACK)//群聊天消息ACK
	//end
	//add zhengnh 2009-12-24 用户新入群时获取该群消息的最大ID
	COMMAND_ENTRY(WY_GET_GROUPMSG_LASTID)
	COMMAND_ENTRY(WY_BROADCAST_MSG)//向多个好友发送多条消息

	//end

	COMMAND_ENTRY_INDEX(WY_SRV_USER_ONLINE, 0x30)//48 上线通知
	COMMAND_ENTRY(WY_SRV_USER_OFFLINE) //下线通知
	COMMAND_ENTRY(WY_SRV_MULTI_ONLINE) //获取在线好友列表
	COMMAND_ENTRY(WY_SRV_STATUS_CHANGED) // 状态改变通知
	COMMAND_ENTRY_INDEX(WY_SRV_STATUS_CHANGED_EX, 0x35)
	//add zhengnh 2009-12-4 通知好友头像改变通知
	COMMAND_ENTRY_INDEX(WY_SRV_MULTI_PIC,0x35)
	COMMAND_ENTRY_INDEX(WY_SUBSCRIBED, 0x36)
	//end

	//@TODO: CHENML ADD 2008-6-27 自动重新启动
	COMMAND_ENTRY_INDEX(WY_SRV_NEXT_TIME, 0x40)  //整点
	COMMAND_ENTRY_INDEX(WY_SRV_RESTART_TIME, 0x41) //重新启动时间

	//END
	COMMAND_ENTRY_INDEX(WY_GET_WORKTIME, 0x42)	//获得上班时间
	COMMAND_ENTRY_INDEX(WY_GET_LOGININFO, 0x43)	//获得登陆信息

	COMMAND_ENTRY_INDEX(WY_GET_MBPASSWD, 0x050)
	COMMAND_ENTRY(WY_GET_EMAILPASSWD)
	COMMAND_ENTRY(WY_GET_MBPASSWD_DIRECT)
	COMMAND_ENTRY(WY_GET_EMAILPASSWD_DIRECT)
	COMMAND_ENTRY(WY_GET_VISUALINFO)     //获取形象秀时间 2004-04-28
	COMMAND_ENTRY(WY_GET_BUSSIP)         //获取业务服务器的ip
	COMMAND_ENTRY(WY_GET_SERVICE_FRD)//获得客服好友2004-07-19
	COMMAND_ENTRY(WY_SET_VISUALINFO) //设置形象秀的相关信息

	//绑定命令
	COMMAND_ENTRY_INDEX(WY_BIND_MOBILE, 0x070)
	COMMAND_ENTRY(WY_BIND_EMAIL)
	COMMAND_ENTRY(WY_BIND_GAME)
	COMMAND_ENTRY(WY_BIND_QQ)
	COMMAND_ENTRY(WY_CHECK_BINDSTATUS)
	COMMAND_ENTRY(WY_VERIFY_CHECKCODE)     //*//_LQP_2004-04-06{业务服务器校验验证串}
	COMMAND_ENTRY(WY_SET_USERINFO)         //*//_LQP_2004-04-07{设置用户资料}
	COMMAND_ENTRY(WY_GET_OFFLINEMSG)       //*//_LQP_2004-04-07{获得用户不在线时收到的消息}2

	COMMAND_ENTRY(WY_CHECK_MOBILE_VERIFYCODE)//*//_LQP_2004-04-09{校验手机与email输入的验证码
	COMMAND_ENTRY(WY_CHECK_EMAIL_VERIFYCODE)//*//}
	COMMAND_ENTRY(WY_CHECK_GAME_VERIFYCODE)

	COMMAND_ENTRY_INDEX(WY_SMS_MSGTEXT, 0x080)//手机短信
	COMMAND_ENTRY(WY_CHECK_ACCOUNT_UNIQUE)
	COMMAND_ENTRY(WY_REGISTER)
	COMMAND_ENTRY(WY_91U_VERIFY)
	COMMAND_ENTRY(WY_TREEBC_MSG)//分级广播消息
	COMMAND_ENTRY(WY_GET_ALL_DEPARTID)//获得所以下级部门
	COMMAND_ENTRY(WY_GET_CHANNEL)//获得频道信息

	COMMAND_ENTRY_INDEX(WY_ZMD_ADD_POINTS, 0x90)//智买盗用户增加的点用

	//*//_yzs_2004-03-28 {
	COMMAND_ENTRY_INDEX(WY_FRIEND_DEPT_CHANGE, 0x91) // 好友改变到组
	//*//_yzs }
	COMMAND_ENTRY_INDEX(WY_CONNECT_P2P, 0x0b3)
	COMMAND_ENTRY(WY_CONNECT_P2U)//网络U盘

	COMMAND_ENTRY_INDEX(WY_P2P_STREAM, 0xb6)

	// 2009-8-5 hj
	COMMAND_ENTRY_INDEX(WY_P2P_NATTRAV, 0xb7)	// 获取外网端口
	COMMAND_ENTRY_INDEX(WY_P2P_NATTRAV_ACK, 0xb8)
	COMMAND_ENTRY_INDEX(WY_P2P_UDPCONNECTING, 0xb9) // 客户端双方尝试直连同时打洞
	COMMAND_ENTRY_INDEX(WY_P2P_PUNCHINGSUCCESS, 0xba) // 告诉服务器打洞成功
	COMMAND_ENTRY_INDEX(WY_P2P_UDPCONNECTED, 0xbb)	// 服务器通知双方客户端已连接



	//取消绑定命令
	COMMAND_ENTRY_INDEX(WY_CANCEL_BIND_MOBILE, 0x0100)
	COMMAND_ENTRY(WY_CANCEL_BIND_EMAIL)
	COMMAND_ENTRY(WY_CANCEL_BIND_GAME)
	COMMAND_ENTRY(WY_CANCEL_BIND_QQ)
	//*//_yzs_2004-04-06 {
	COMMAND_ENTRY(WY_SET_FRIEND_OF_FRIEND) // 设置自己好友对好友的好友功能的开放状态
	COMMAND_ENTRY(WY_GET_FRIEND_OF_FRIEND_LIST) // 获得好友的好友列表
	// yzs_2004-6-1 上午 09:22:26{
	COMMAND_ENTRY(WY_GAME_PLAYER_INFO)	//　游戏玩家信息
	// yzs_2004-7-8 下午 03:34:30
	COMMAND_ENTRY(WY_GET_91GAME_LIST)	//获得小游戏列表
	// yzs_2004-8-16 下午 02:32:24
	COMMAND_ENTRY(WY_LSTFRDEX)	// 获得好友列表扩展　加入好友类型
	COMMAND_ENTRY(WY_ADDFRDEX)	// 加好友扩展　加入好友类型
	COMMAND_ENTRY(WY_REMFRDEX)	// 删除好友扩展　加入好友类型
	// yzs_2004-9-3 上午 10:35:07
	COMMAND_ENTRY(WY_SEARCH_FRIENDEX) // 查找扩展
	//*//_yzs }


	COMMAND_ENTRY_INDEX(WY_BUG, 0x0500)
	COMMAND_ENTRY_INDEX(WY_TESTCONNECT, 0x0600)//测试连接是否有效
	COMMAND_ENTRY_INDEX(WY_SERVER_BUSY, 0x0610)//服务器忙

	//@TODO: CHENML ADD 2008-8-2 状态维护
	COMMAND_ENTRY_INDEX(WY_SERVER_KILL, 0x0611)	//服务端的session已被丢

	//END

	COMMAND_ENTRY_INDEX(WY_GET_91SOFT_LIST, 0x0700)// yzs_2004-12-21 上午 11:26:33
	COMMAND_ENTRY_INDEX(WY_GET_91GAME_XML, 0x0701)// yzs_2004-12-24 上午 10:52:45

	//*//_ZCS_2004-07-07
	COMMAND_ENTRY_INDEX(WY_UDISK_BASE, 0x0E00)
	COMMAND_ENTRY(WY_UDISK_GET_INFO)
	COMMAND_ENTRY(WY_UDISK_FILE_UPLOAD)
	COMMAND_ENTRY(WY_UDISK_FILE_DOWNLOAD)
	COMMAND_ENTRY(WY_UDISK_FILE_DELETE)
	COMMAND_ENTRY(WY_UDISK_FILE_DELETE_BY_OTHER)
	COMMAND_ENTRY(WY_UDISK_FILE_DELETE_USERVER_RET)
	COMMAND_ENTRY(WY_UDISK_FILE_DELETE_91SERVER_RET)

	COMMAND_ENTRY(WY_UDISK_FILE_CHANGENAME)

	COMMAND_ENTRY(WY_UDISK_DIR_CREATE)
	COMMAND_ENTRY(WY_UDISK_DIR_DELETE)
	COMMAND_ENTRY(WY_UDISK_DIR_CHANGENAME)

	COMMAND_ENTRY(WY_UDISK_GET_UNRECEIVED_FILE_INFO)

	COMMAND_ENTRY(WY_UDISK_FILE_DELIVER)

	COMMAND_ENTRY_INDEX(WY_UDISK_CHECKCODE_FROM_OTHER_SERVER, 0x0e99)
	COMMAND_ENTRY(WY_UDISK_CHECKCODE_FROM_OTHER_SERVER_RET)

	COMMAND_ENTRY(WY_UDISK_DELETE_REMOTE_TRANSMIT_MSG)
	//	COMMAND_ENTRY(WY_UDISK_CREATE)
	//*//_ZCS_2004-07-07

	//_{语音相关
	COMMAND_ENTRY_INDEX(WY_VOICE_GETUSERINFO, 0x1000)//取语音的用户名信息
	COMMAND_ENTRY_INDEX(WY_VOICE_ENDCALL, 0x1001)//结束呼叫
	COMMAND_ENTRY_INDEX(WY_VOICE_GETINFO, 0X1002)//语音厂商信息（客户端登陆时向服务端取）

	COMMAND_ENTRY_INDEX(WY_VOICE_ISHAVEVIDEO, 0x1050)//是否有视频
		//_}

	COMMAND_ENTRY_INDEX(TCP_CMD_SENDMSG, 0x2000)//发送手机短消息

	COMMAND_ENTRY_INDEX(WY_GET_91U_RES_URLS, 0x2100)// yzs_2004-11-19 下午 03:24:22

		//林巧平 10000--11000{
	COMMAND_ENTRY_INDEX(WY_TRANSFER_FRD, 10000)
	COMMAND_ENTRY_INDEX(WY_CVR2, 10001)

	COMMAND_ENTRY_INDEX(WY_END, 11000)
	//林巧平 10000--11000}

		// 杨振森 10001--12000 {
	COMMAND_ENTRY_INDEX(WY_LSTFRD2, 11001)
	COMMAND_ENTRY_INDEX(WY_CVR3, 11002)
	COMMAND_ENTRY_INDEX(WY_GET_GAME_ONLINE_XML, 11003)
	COMMAND_ENTRY_INDEX(WY_LSTFRD3, 11004)
	COMMAND_ENTRY_INDEX(WY_GET_NDHONOR_XML, 11005)
	COMMAND_ENTRY_INDEX(WY_GET_COMM_TEXT, 11006)
	COMMAND_ENTRY_INDEX(WY_GAMESYNC_ADDFRD, 11007)
	COMMAND_ENTRY_INDEX(WY_SET_TQGAMEINFO, 11008)
	COMMAND_ENTRY_INDEX(WY_NEW_TQGAMEINFO, 11009)
	COMMAND_ENTRY_INDEX(WY_GET_NDHONOR_ME, 11010)

	COMMAND_ENTRY_INDEX(WY_YZS_END, 12000)
	// 杨振森 10001--12000 }
	//add by wbh
	COMMAND_ENTRY_INDEX(WY_SET_MSGRANK, 12050) //client->server  : srcuin, dstuin, rank(1,-1);
	COMMAND_ENTRY(WY_SEND_MSGRANK_2C_SRC) //server->client   : num [ dstuin, ]n ; //源是 自己
	COMMAND_ENTRY(WY_SEND_MSGRANK_2C_DST) //server->client   : num [ srcUin, ]n ; //目标是自己
	COMMAND_ENTRY(WY_SEND_MSGRANK_2C_SET)  //server->client  : srcuin, dstuin, rank(1,-1);
	COMMAND_ENTRY(WY_SEND_MSGRANK_2C_RIGTH)  //server->client  : 获取 权限;//有权限发送该消息,否则不发送;

	COMMAND_ENTRY_INDEX(WY_SEN_MSGRANK_END, 12090)
	// end wbh;
	COMMAND_ENTRY(WY_TOOL_TMP_CHANNEL_PSW) // client->server ;  <<Toolname<< strPSW;
	//add by dwj : for 配置信息表，包括配置群截图服务器等
	COMMAND_ENTRY(WY_GET_CONFIG) //获取配置信息（tbconfig）//cmd - num - key - value - key -value ...
	COMMAND_ENTRY(WY_SAVE_PDEPT)
	COMMAND_ENTRY(WY_GET_PDEPT)
	//@TODO: CHENML ADD 2008-7-21 启动速度优化
	COMMAND_ENTRY(WY_NOTIFY_READY) //登录准备完成
	COMMAND_ENTRY_INDEX(WY_STATE_GET_OVER, 12090+13) //chenbo 2008.8.3 好友在线状态下发完毕。
	//END
	//Modified by dwj 2008-10-14
	COMMAND_ENTRY(WY_RECORD_VOLIATE)//记录违反规定聊天的
	//End
	COMMAND_ENTRY(WY_GET_AREA_INFO)         //add by chenbo [2008.10.15] 获取办公区域信息
	COMMAND_ENTRY(WY_GET_NDDEPT_INFO)       //获取公司DEPT信息
	//============begin===============
	//author:lw
	//date:	2008:10:16
	//Note:	设置下次提醒更新照片的时间
	COMMAND_ENTRY_INDEX(WY_SET_PIC_UPDATE_AWOKE, 20000)
	//===========End==================
	COMMAND_ENTRY_INDEX(WY_LOG_SEND_FILE, 20002)
	//2009-01 chenhd add for 群发文件
	COMMAND_ENTRY_INDEX(WY_GROUP_SEND_FILE, 20003)
	COMMAND_ENTRY_INDEX(WY_UPDATE_GROUP_FILE, 20004)
	//2009-01 chenhd end
	 //2009-01 chenhd add for 群临时聊天功能
	COMMAND_ENTRY_INDEX(WY_GROUP_SIMPLE_INFO, 20005)
	COMMAND_ENTRY_INDEX(WY_GROUP_TMP_CHAT_ADD, 20006)
	COMMAND_ENTRY_INDEX(WY_GROUP_TMP_CHAT_DEL, 20007)
	 //2009-01 chenhd end
	//@TODO:Huanghe ADD 2008-11-7 获取，设置个性签名
	COMMAND_ENTRY(WY_SET_PERSONALIZEDSIGN)   //设置个性签名
	//END
	//@ADD CHENML 2009-3-3 提供91通行证认证
	COMMAND_ENTRY(WY_NETAUTH_OPEN) //查找对应的uin


// 文件传输
COMMAND_ENTRY_INDEX(	WY_FILETRANSFER_FIRST,			21000	)
COMMAND_ENTRY(	WY_FILETRANSFER_OFFER_REQUEST	)					// 请求发送文件
COMMAND_ENTRY(	WY_FILETRANSFER_OFFER_RESPONSE	)
COMMAND_ENTRY(	WY_FILETRANSFER_OFFER_ACK	)						// ACK
COMMAND_ENTRY(	WY_FILETRANSFER_READY_REQUEST	)					// 准备发送文件
COMMAND_ENTRY(	WY_FILETRANSFER_READY_RESPONSE	)
COMMAND_ENTRY(	WY_FILETRANSFER_CLOSE	)							// 关闭或取消发送文件
COMMAND_ENTRY_INDEX(	WY_FILETRANSFER_LAST,			21099	)



COMMAND_ENTRY_INDEX(	WY_MESSAGE,							20480	)
COMMAND_ENTRY_INDEX(	WY_MESSAGE_ARRIVED,		20481	)
COMMAND_ENTRY_INDEX(	WY_MESSAGE_COPY,				20482	)


	// new added 2009-11-20
	COMMAND_ENTRY_INDEX(WY_OFFLINEMSG_ACK, 30001)
	COMMAND_ENTRY_INDEX(WY_GET_NEWFRD_STATUS, 30002)
	COMMAND_ENTRY_INDEX(WY_GETUSR_EXT, 30003) // add zhengnh 2009-12-30 获取用户扩展资料
	COMMAND_ENTRY_INDEX(WY_NICK_NOTIFY, 30005)//用户昵称改变通知
	COMMAND_ENTRY_INDEX(WY_INVALID_COMMAND, 30006)//add zhengnh 2010-01-08 处理服务器不处理的命令
	COMMAND_ENTRY_INDEX(WY_MOOD_NOTIFY, 30007)//add zhengnh 2010-01-15 用户心情改变通知
	COMMAND_ENTRY_INDEX(WY_PERSONAL_SIGN_NOTIFY, 30010) //个人签名
 	COMMAND_ENTRY_INDEX(WY_PICTURE_NOTIFY, 30011)//add zhengnh 2010-01-15 用户头像改变通知

 	COMMAND_ENTRY_INDEX(WY_MDICNLVL_NOTIFY, 30020) //game unas notify

	COMMAND_ENTRY_INDEX(WY_OFFLINEMSG_ACK_ONE, 30030)


	//add zhengnh 2010-01-08 处理用户群数量命令
	//Add By chenzhao 2010-01-08
	COMMAND_ENTRY_INDEX(WY_GET_GROUPS_RELATE_NUM, 32000)//获取某用户创建群和加入群的数量
	COMMAND_ENTRY(WY_GROUP_AUTHJOINNUMBER)//创建群或解散群
	COMMAND_ENTRY(WY_GROUP_JOINNUMBER)//加入 群或退出群
	COMMAND_ENTRY(WY_GROUP_AUTHNUMBER)//转移群
	COMMAND_ENTRY(WY_GROUPMEMBER_AUTH)// 获取某个用户的创建群和加入群的数量
	//End

	COMMAND_ENTRY_INDEX(WY_GROUP_INIT, 32010) // 初始化群
	COMMAND_ENTRY_INDEX(WY_GROUP_TALK_INIT, 32011) // 初始化讨论组


	//WARNING: DONOT exceed 32768

	// --------------------- 系统消息 ---------------------
	COMMAND_ENTRY_INDEX(WY_SYSMSG_MASK, 0x8000)
	COMMAND_ENTRY_INDEX(WY_SYSMSG_INIT, 0x8001)				// 初始化系统消息，发送系统消息查询需要的用户资料属性
	COMMAND_ENTRY(WY_SYSMSG_SRV_MSG)	// 系统消息
	COMMAND_ENTRY(WY_SYSMSG_ACK)	// 应答IMS的消息
	COMMAND_ENTRY(WY_SYSMSG_CREATE)	// 创建系统消息
	COMMAND_ENTRY(WY_SYSMSG_GET_PERMESSION)	// 获取创建系统消息权限

	// old
	COMMAND_ENTRY_INDEX(WY_MSG_RECVSYS_IMSTOSMS, 0x80F1) //接受系统消息
	COMMAND_ENTRY(WY_MSG_SEARCHSYS_IMSTOSMS) // 查询系统消息
	COMMAND_ENTRY(WY_MSG_SENDSYSALL_SMSTOIMS) //全网消息发送
	COMMAND_ENTRY(WY_MSG_MOSTUSR_SMSTOIMS) //大用户量的消息
	COMMAND_ENTRY(WY_MSG_SENDSYSSAMLL_SMSTOIMS) //系统消息发送－人数少
	COMMAND_ENTRY(WY_MSG_ACK_SMS)//应答IMS的消息
	COMMAND_ENTRY(WY_GET_SYSMSG_PERMESSION)//获取建立系统消息权限
	//End

	// --------------------- 多点登陆消息 ---------------------
	COMMAND_ENTRY_INDEX(WY_MULTPOIINT_MASK, 0x9000)
	COMMAND_ENTRY_INDEX(WY_MULTPOINT_LOGIN, 0x9000)  // 多点登陆
	COMMAND_ENTRY(WY_MULTPOINT_FORCE_OFFLINE) // 强迫某登陆点下线
	COMMAND_ENTRY(WY_MULTPOINT_FORCE_ALLOTHERS_OFFLINE) // 强迫其它所有登陆点下线
	COMMAND_ENTRY(WY_MULTPOINT_SUBSCRIBE_FRDS_ONLINE) // 订阅获取多点在线好友列表
	COMMAND_ENTRY(WY_MULTPOINT_OWN_MSG) // 发送聊天消息到自己的其他登陆点
	COMMAND_ENTRY(WY_MULTPOINT_MSG_ACK) // 发送对某个登陆点聊天确认
	COMMAND_ENTRY(WY_MULTPOINT_SRV_USER_OFFLINE) // 多点下线通知
	COMMAND_ENTRY(WY_MULTPOINT_DESC_CHANGED)  //多点描述改变
	COMMAND_ENTRY(WY_MULTPOINT_SRV_DESC_CHANGED) //多点描述改变通知
	COMMAND_ENTRY(WY_MULTPOINT_MSG) // 多点聊天
	COMMAND_ENTRY(WY_MULTPOINT_RESERVED)
	COMMAND_ENTRY(WY_MULTPOINT_LOGIN_AND_FORCEONE_OFFLINE) // 多点登陆并选择强制一个下线
	COMMAND_ENTRY(WY_MULTPOINT_SUB_STATUS_CHANGED) // 子状态改变
	COMMAND_ENTRY(WY_MULTPOINT_MSG_ACK_ONE) // 发送对某个登陆点聊天确认

	// 转发通知到自己的其他登录点
	COMMAND_ENTRY_INDEX(WY_MULTPOINT_NOTIFYSELF_START, 0x9900)
	COMMAND_ENTRY(WY_MULTPOINT_NOTIFYSELF_ADD_FRD) //添加好友后通知本人其他登陆点
	COMMAND_ENTRY(WY_MULTPOINT_NOTIFYSELF_RENAME_FRD) //重命名好友后通知本人其他登陆点
	COMMAND_ENTRY(WY_MULTPOINT_NOTIFYSELF_ADD_FRD_GROUP) //添加好友组后通知本人其他登陆点
	COMMAND_ENTRY(WY_MULTPOINT_NOTIFYSELF_RENAME_FRD_GROUP) //重命名好友组后通知本人其他登陆点
	COMMAND_ENTRY(WY_MULTPOINT_NOTIFYSELF_MOVE_FRD_TO_GROUP) //移动好友到其他组后通知本人其他登陆点
	COMMAND_ENTRY(WY_MULTPOINT_NOTIFYSELF_DEL_FRD) // 删除好友通知多点
	COMMAND_ENTRY(WY_MULTPOINT_NOTIFYSELF_DEL_FRD_GROUP) // 删除分组通知多点
	COMMAND_ENTRY(WY_MULTPOINT_NOTIFYSELF_USERINFO_MODIFY) //用户个人资料修改
	COMMAND_ENTRY(WY_MULTPOINT_NOTIFYSELF_CANCEL_RECVFILE) //取消接收文件
	COMMAND_ENTRY_INDEX(WY_MULTPOINT_NOTIFYSELF_END, 0x9999)


	// --------------------- 语音消息 ---------------------
	COMMAND_ENTRY_INDEX(WY_AUDIO_MASK, 0xA000)
	//二人语音
	COMMAND_ENTRY_INDEX(WY_AUDIO_CALL, 0xA001)			//主叫端向IMS发起语音请求
	COMMAND_ENTRY(WY_AUDIO_CALLBECANCELED_BYIMS)		//主叫端被IMS取消语音请求
	COMMAND_ENTRY(WY_AUDIO_CALLBECANCELED_BYHOST)	//被主叫端取消语音请求
	COMMAND_ENTRY(WY_AUDIO_CALLBECANCELED_BYCALLED) //被叫方一点同意或拒绝，其它点取消
	COMMAND_ENTRY(WY_AUDIO_CALLCANCEL)			//主叫端取消语音请求
	COMMAND_ENTRY(WY_AUDIO_BECALLED)				//被叫
	COMMAND_ENTRY(WY_AUDIO_BEREFUSED)			//被拒绝
	COMMAND_ENTRY(WY_AUDIO_REFUSE)					//拒绝
	COMMAND_ENTRY(WY_AUDIO_ACCEPT)					//接受
	COMMAND_ENTRY(WY_AUDIO_BEACCEPTED)			//被接受
	COMMAND_ENTRY(WY_AUDIO_UPDATESTATUS)	//更新语音状态
	COMMAND_ENTRY(WY_AUDIO_INVITE)					//发起语音邀请
	COMMAND_ENTRY(WY_AUDIO_BEINVITED)			//被邀请
	COMMAND_ENTRY(WY_AUDIO_TERMINATE)			//结束语音聊天
	COMMAND_ENTRY(WY_AUDIO_BETERMINATED)	//被结束语音聊天
	//多人语音
	COMMAND_ENTRY_INDEX(WY_AUDIOGROUP_QUREYROOM, 0xA101)		//查询群相关的语音聊天室ID
	COMMAND_ENTRY(WY_AUDIOGROUP_SAVEROOMID)			//保存语音聊天室ID
	COMMAND_ENTRY(WY_AUDIOGROUP_LEAVEROOM)				//离开语音聊天室（最后一个时要注销语音聊天室）
	COMMAND_ENTRY(WY_AUDIOGROUP_UPDATESTATUS)		//更新语音状态
	COMMAND_ENTRY(WY_AUDIOGROUP_MEMBERSTATUS)		//群成员的语音状态通知
	COMMAND_ENTRY(WY_AUDIOGROUP_QRYMBERSTATUS)	//查询群组成员的语音状态
	COMMAND_ENTRY(WY_GROUPTALK_AUDIO_INVITEONE) //add zhengnh 建立多人语音聊天室后邀请用户进入聊天


	//--------------------- UAP 适配通知消息 ---------------------
	COMMAND_ENTRY_INDEX(WY_UNAS_MASK, 			0xC000)
	COMMAND_ENTRY_INDEX(WY_UNAS_NOTIFY, 	0xC001)
	COMMAND_ENTRY_INDEX(WY_UNAS_EHR_MSG, 	0xC003)
	COMMAND_ENTRY_INDEX(WY_UNAS_ECP_MSG, 	0xC004)
	COMMAND_ENTRY_INDEX(WY_UNAS_ORG_MSG_OLD, 0xC005)
	COMMAND_ENTRY_INDEX(WY_UNAS_ORG_MSG,	0xC008)
	COMMAND_ENTRY_INDEX(WY_UNAS_ORG_GROUP_MSG,	0xC009)


	// --------------------- 测试消息 ---------------------
	COMMAND_ENTRY_INDEX(WY_TEST_MASK, 0xD000)
	COMMAND_ENTRY_INDEX(WY_TEST_ECHO, 0xD000)
	COMMAND_ENTRY(WY_STATISTICS_CLEAR) // 清空计数器
	COMMAND_ENTRY(WY_STATISTICS_CLEAR_CMD) // 清空某个命令的计数器
	COMMAND_ENTRY(WY_STATISTICS_CMD) // 获取某命令的计数
	COMMAND_ENTRY(WY_TEST_GETFRDSTATUS)


	// --------------------- S2S消息 ---------------------
	COMMAND_ENTRY_INDEX(WY_S2S_MASK, 0xE000)
	COMMAND_ENTRY(WY_S2S_HEARTBEAT)
	COMMAND_ENTRY(WY_S2S_HEARTBEAT_RET)

	// MSS
	// 个人离线消息
	COMMAND_ENTRY_INDEX(WY_MSS_MASK, 0xE100)
	COMMAND_ENTRY(WY_MSS_OFFLINE_MSG_GET)				// 获取离线消息
	COMMAND_ENTRY(WY_MSS_OFFLINE_MSG_SAVE)			// 保存离线消息
	COMMAND_ENTRY(WY_MSS_OFFLINE_MSG_DELETE)		// 删除离线消息
	COMMAND_ENTRY(WY_MSS_OFFLINE_MSG_DELETE_ONE)		// 删除离线消息

	// 群消息
	COMMAND_ENTRY_INDEX(WY_MSS_OFFLINE_GROUP_MSG_GET, 0xE111)					// 获取群消息
	COMMAND_ENTRY(WY_MSS_OFFLINE_GROUP_MSG_SAVE)				// 保存群消息
	COMMAND_ENTRY(WY_MSS_OFFLINE_GROUP_MSG_MAXID)				// 获取群最大消息id
	//消息存储
	COMMAND_ENTRY_INDEX(WY_MSS_MSG_GET, 0xE121)									// 获取消息
	COMMAND_ENTRY(WY_MSS_MSG_SAVE)								// 保存消息
	COMMAND_ENTRY(WY_MSS_MSG_DELETE)							// 删除消息


	//
	//custom_service
	//
	COMMAND_ENTRY_INDEX(WY_CS_MASK, 0xE300)
	COMMAND_ENTRY(WY_CS_AGENT_PRESENCE)
	COMMAND_ENTRY(WY_CS_AGENT_ABSENCE)
	COMMAND_ENTRY(WY_CS_AGENT_ACCEPT)
	COMMAND_ENTRY(WY_CS_AGENT_REFUSE)
	COMMAND_ENTRY(WY_CS_AGENT_REDIRECT)
	COMMAND_ENTRY(WY_CS_AGENT_GET_QUEUE)
	COMMAND_ENTRY(WY_CS_AGENT_GET_QUEUEAGENT)
	COMMAND_ENTRY(WY_CS_AGENT_USERAMOUNT)
	COMMAND_ENTRY(WY_CS_AGENT_OFFLINE)

	COMMAND_ENTRY_INDEX(WY_CS_USER_SCORE,0xE311)
	COMMAND_ENTRY(WY_CS_USER_DEPART)
	COMMAND_ENTRY(WY_CS_USER_JOIN)

	COMMAND_ENTRY_INDEX(WY_CS_CONVERSATION_END,0xE321)
	COMMAND_ENTRY(WY_CS_SEND_MSG)
	COMMAND_ENTRY(WY_CS_GET_MSG)
	COMMAND_ENTRY(WY_CS_HEARTBEAT)
	COMMAND_ENTRY(WY_CS_HEARTBEAT_ACK)

	COMMAND_ENTRY_INDEX(WY_CS_CLIENT_INVITE,0xE331)
	COMMAND_ENTRY(WY_CS_CLIENT_USERINFO)
	COMMAND_ENTRY(WY_CS_CLIENT_DELCVS)
	COMMAND_ENTRY(WY_CS_CLIENT_NEWCVS)
	COMMAND_ENTRY(WY_CS_CLIENT_MSG)




	// --------------------- 群消息 ---------------------
	COMMAND_ENTRY_INDEX(WY_GROUP_MASK, 0xF000)
	COMMAND_ENTRY_INDEX(WY_GROUP_START, 0xF000)  //群服务开始，无实际业务含义
	COMMAND_ENTRY(WY_GROUP_HEARBEAT)  //用于群客户端发送心跳
	COMMAND_ENTRY(WY_GROUP_CONNECT)	  //用于群客户端初始连接，未连接不能进行业务操作
	COMMAND_ENTRY(WY_GROUP_ONLINE_USER)
	COMMAND_ENTRY(WY_GROUP_STATUS)
	COMMAND_ENTRY(WY_GROUP_MEMBER_STATUS)
	COMMAND_ENTRY(WY_GROUP_BCMSG)
	COMMAND_ENTRY(WY_GROUP_CREATE)
	COMMAND_ENTRY(WY_GROUP_INVITE)
	COMMAND_ENTRY(WY_GROUP_INVITE_ANSWER)
	COMMAND_ENTRY(WY_GROUP_MEMBER_INVITE_ENTRY)
	COMMAND_ENTRY(WY_GROUP_ENTRY)
	COMMAND_ENTRY(WY_GROUP_ENTRY_REQUEST_ANSWER)
	COMMAND_ENTRY(WY_GROUP_MEMBER_ENTRY)
	COMMAND_ENTRY(WY_GROUP_MEMBER_DELETE)
	COMMAND_ENTRY(WY_GROUP_LEAVE)
	COMMAND_ENTRY(WY_GROUP_MEMBER_LEAVE)
	COMMAND_ENTRY(WY_GROUP_CHANGEMANAGER)
	COMMAND_ENTRY(WY_GROUP_MEMBER_CHANGEMANAGER)
	COMMAND_ENTRY(WY_GROUP_ABANDONMANAGEMENT)
	COMMAND_ENTRY(WY_GROUP_NEWMANAGER)
	COMMAND_ENTRY(WY_GROUP_DELETE)
	COMMAND_ENTRY(WY_GROUP_DELETE_MESSAGE)
	COMMAND_ENTRY(WY_GROUP_UPDATE)
	COMMAND_ENTRY(WY_GROUP_GET_OFFLINE_MSG)
	COMMAND_ENTRY(WY_GROUP_RECEIVE_STATUS)//接收用户状态
	COMMAND_ENTRY(WY_GROUP_RECEIVE_STATUS_RET)//接收用户状态回包
	COMMAND_ENTRY(WY_GROUP_CANCEL_RECEIVE_STATUS)//取消接受用户状态
	COMMAND_ENTRY(WY_GROUP_CANCEL_RECEIVE_STATUS_RET)//取消接收用户状态回包
	COMMAND_ENTRY(WY_GROUP_ONLINE_COUNT) // 获取在线数量
	COMMAND_ENTRY(WY_GROUP_CLEAR_IMS_UIDS)	//清除ims下的所有用户

			//讨论组
	COMMAND_ENTRY_INDEX(WY_GROUP_TALK_START, WY_GROUP_START + 501)
	COMMAND_ENTRY(WY_GROUP_TALK_CREATE)
	COMMAND_ENTRY(WY_GROUP_TALK_INVITE)
	COMMAND_ENTRY(WY_GROUP_TALK_STATUS)
	COMMAND_ENTRY(WY_GROUP_TALK_BCMSG)
	COMMAND_ENTRY(WY_GROUP_TALK_LEAVE)
	COMMAND_ENTRY(WY_GROUP_TALK_GET_USER)
	//2010-01-15 新增讨论组状态相关命令
	COMMAND_ENTRY(WY_GROUP_TALK_RECEIVE_STATUS)
	COMMAND_ENTRY(WY_GROUP_TALK_RECEIVE_STATUS_RET)
	COMMAND_ENTRY(WY_GROUP_TALK_CANCEL_RECEIVE_STATUS)
	COMMAND_ENTRY(WY_GROUP_TALK_CANCEL_RECEIVE_STATUS_RET)
	COMMAND_ENTRY(WY_GROUP_GLOBAL_TALK_GET_GROUPS)
	COMMAND_ENTRY(WY_GROUP_GLOBAL_TALK_GET_GROUPS_RET)
	//2010-05-07新增语音相关命令
	COMMAND_ENTRY(WY_GROUP_TALK_AUDIO_INVITETOROOM)
	COMMAND_ENTRY(WY_GROUP_TALK_AUDIO_INVITETOROOM_RET)
	COMMAND_ENTRY(WY_GROUP_TALK_AUDIO_CANCEL)
	COMMAND_ENTRY(WY_GROUP_TALK_AUDIO_CANCEL_RET)
	COMMAND_ENTRY(WY_GROUP_TALK_AUDIO_ACCEPT)
	COMMAND_ENTRY(WY_GROUP_TALK_AUDIO_ACCEPT_RET)
	COMMAND_ENTRY(WY_GROUP_TALK_AUDIO_REFUSE)
	COMMAND_ENTRY(WY_GROUP_TALK_AUDIO_REFUSE_RET)
	COMMAND_ENTRY(WY_GROUP_TALK_AUDIO_HANGUP)
	COMMAND_ENTRY(WY_GROUP_TALK_AUDIO_HANGUP_RET)
	COMMAND_ENTRY(WY_GROUPTALK_AUDIO_STATUS_NOTIFY)
	COMMAND_ENTRY(WY_GROUPTALK_AUDIO_STATUS_NOTIFY_RET)
	COMMAND_ENTRY(WY_GROUP_AUDIOTALK_CREATE)
	COMMAND_ENTRY(WY_GROUP_AUDIOTALK_CREATE_RET)
	COMMAND_ENTRY_INDEX(WY_GROUP_TALK_END, WY_GROUP_START + 1000)
	//全局库
	COMMAND_ENTRY_INDEX(WY_GROUP_GLOBAL_START, WY_GROUP_START + 1001)
	COMMAND_ENTRY(WY_GROUP_GLOBAL_REG_GROUP)
	COMMAND_ENTRY(WY_GROUP_GLOBAL_REG_GROUP_RET)
	COMMAND_ENTRY(WY_GROUP_GLOBAL_REM_GROUP)
	COMMAND_ENTRY(WY_GROUP_GLOBAL_REM_GROUP_RET)
	COMMAND_ENTRY(WY_GROUP_GLOBAL_GMS_IMS)
	COMMAND_ENTRY(WY_GROUP_GLOBAL_GMS_IMS_RET)
	COMMAND_ENTRY(WY_GROUP_GLOBAL_TALK_GID_GMS)
	COMMAND_ENTRY(WY_GROUP_GLOBAL_TALK_GID_GMS_RET)
	COMMAND_ENTRY(WY_GROUP_GLOBAL_GID_GMS)
	COMMAND_ENTRY(WY_GROUP_GLOBAL_GID_GMS_RET)
	COMMAND_ENTRY(WY_GROUP_GLOBAL_REG_TALK)
	COMMAND_ENTRY(WY_GROUP_GLOBAL_REG_TALK_RET)
	COMMAND_ENTRY_INDEX(WY_GROUP_GLOBAL_END, WY_GROUP_START + 1200)
	//2010-01-15 新增 在群服务器上更新群资料相关 命令
	COMMAND_ENTRY_INDEX(WY_GROUP_END, WY_GROUP_START + 3000)  //群服务结束，无实际业务含义

END_COMMANDS()

#undef DECLARE_COMMANDS
#undef COMMAND_ENTRY_INDEX
#undef COMMAND_ENTRY
#undef END_COMMANDS

#endif /* _COMMON_CMD_H_ */


