CXX=g++
CC=gcc

CXX_FLAG= -O0 -g3 -Wall -fmessage-length=0 -MMD -MP -DHAVE_CXX_STDHEADERS -DBOOST_FILESYSTEM_VERSION=2 

#to be configured
SERVERHOME = /home/91u/91userver
COMMON_PROJECT=
#COMMON_PROJECT=$(SERVERHOME)/custom_service/client


#build project depend on home below
BOOST_HOME = /usr/local/boost_1_48_0
LIBEVENT_HOME = ./
MYSQL_HOME = /usr/local/mysql
MYSQLPP_HOME = ./

#lib in upfloder 
NETBASE_HOME = $(SERVERHOME)/new/base



INCLUDE= -I/usr/include \
			-I/usr/local/include \
			-I$(BOOST_HOME)/include \
			-I$(NETBASE_HOME)/include \
			-I$(SERVERHOME) \
			-I./include \
			-I./src \
			-I../CustomServiceMsg/include \
			-I$(SERVERHOME)/new/ims/commandlib/include 
		   

LIB = \
		-L$(NETBASE_HOME)/lib \
		-L$(SERVERHOME)/lib \
		-L$(BOOST_HOME)/lib \
		-L/usr/local/lib \
		-L./lib \
		-lCSClient \
		-lnewbase -lcommand \
		-ltbbmalloc -ltbb -levent  -levent_pthreads  -ltcmalloc \
		-lboost_program_options -lboost_filesystem -lboost_thread -lboost_iostreams -lboost_date_time -lboost_system -lboost_log \
		-llog4cpp -lcurses -lexpat   \
		-lz -lbz2 -ldl -llzma -lrt -lpthread -lm -lc -lresolv -lnsl


SRC=$(shell echo src/*.cpp)
OBJ=$(foreach n,$(SRC),obj/src/$(basename $(notdir $(n))).o)

TEST_SRC=$(shell echo test/*.cpp)
TEST_OBJ=$(foreach n,$(TEST_SRC),obj/test/$(basename $(notdir $(n))).o)

OBJS=$(OBJ)





obj/src/%.o:src/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXX_FLAG) -c $(INCLUDE) $< -o $@

obj/test/%.o:test/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXX_FLAG) -c $(INCLUDE) $< -o $@



.PHONY:libCSClient.a

libCSClient.a:$(OBJS)
	@mkdir -p ./lib
	@ar -rv ./lib/$@ $^
	@cp ./lib/$@ $(SERVERHOME)/lib

cstest:$(TEST_OBJ)
	$(CXX) $^ -o $@ $(LIB)
	@echo "Compiled successfully ..."

clean:
	@rm -rf $(OBJS) $(TEST_OBJ) CustomServiceClient 

