#ifndef IMSCMD_H
#define IMSCMD_H


enum CS2IMS_CMD
{

	//copied from imserver: IMS2SCmd.h
	WY_IMS2S_CMD_REQUST_START = 0xC000,
	WY_IMS2S_HEARTBEAT,
	WY_IMS2S_MSGRELAY, // 转发消息
	WY_IMS2S_FRIEND_NOTIFY, // 好友通知

	WY_IMS2S_CMD_REQUST_END,


	WY_IMS2S_CMD_RESPONSE_START = 0xC100,
	WY_IMS2S_HEARTBEAT_RET,
	WY_IMS2S_MSGRELAY_RET,
	WY_IMS2S_FRIEND_NOTIFY_RET,
	WY_IMS2S_CONNECT_BROKEN,

	WY_IMS2S_CMD_RESPONSE_END,

	//the below deprecated
	
	WY_CS2IMS_INVITE_LIST,
	WY_CS2IMS_USER_LIST,
	WY_CS2IMS_USER_DELCVS,
	WY_CS2IMS_AGENT_DELCVS,
	WY_CS2IMS_USER_NEWCVS,
	WY_CS2IMS_MSG,

	WY_CS2IMS_END

};


#endif
